package biz.ezcom.spring.jdbc.dao.api;

import java.util.List;

import biz.ezcom.spring.jdbc.po.User;

public interface IUserDao {
    // 增
    int save(User user);

    int saveAutoGeneratedKey(User user);

    int[] save(List<User> users);

    // 删
    int remove(Integer id);

    // 改
    int modify(User user);

    int[] modifys(List<User> users);

    // 查
    int findCount();

    User find(Integer id);
}
