package biz.ezcom.spring.jdbc.dao.api;

import java.util.List;
import java.util.Map;

import org.springframework.jdbc.support.rowset.SqlRowSet;

import biz.ezcom.spring.jdbc.po.User;

public interface IUserDao {
    // 增
    int save(User user);

    int saveAutoGeneratedKey(User user);

    int[] save(List<User> users);

    // 删
    int remove(Integer id);

    // 改
    int modify(User user);

    int[] modifys(List<User> users);

    // 查
    Map<String, Object> findMapById(Integer id);

    SqlRowSet findSqlRowSetById(Integer id);

    String findUsernameById(Integer id);

    User findUserById(Integer id);

    List<Map<String, Object>> findMaps();

    List<Integer> findIdsByManagerId(Integer managerId);

    List<User> findUsersByRowMapper();

    List<User> findUsersByRowCallbackHandler();

    List<User> findUsersByResultSetExtractor();
}
